[package]
name = "hit_test_file_model"
version = "0.1.0"
authors = ["ll"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.hit]
path = "../indexed_model"